### PR TITLE
Add tool publishing

### LINKED ISSUE #4: publish exe from github actions

### PR DESCRIPTION
**Pull request by wgnf**
Closes #4  
  
This configures the main-project in a way that it can be published as a .NET CLI Tool. Which then can be used using the .NET Tool toolchain (lol) (see the updated README for more information).  
This way users can easily install and use your tool without needing to download any files with proper versioning.  
  
To be able to publish you have to do the following as an author:
1. Sign In to nuget.org using your Microsoft Account
2. When signed in, go to https://www.nuget.org/account/apikeys and create a new key. The "Key Name" can be anything but for the "Glob Pattern" you have to specify the package name(s) that you want this key be for. For this project that should be `sln-items-sync.*`
3. This will then give you your API-Key which can only copy **once**
4. Use this API-Key and create a new "Repository secret" under https://github.com/timabell/sln-items-sync/settings/secrets/actions with the name `NUGET_API_KEY` (see new `publish.yml`) file

This should be enough to be able to publish your tool to nuget.org when pushing a version tag (such as `v1.22.333` or as a preview `v1.22.333-preview1`)

Let me know if you need anything to be changed :)

### CODE REVIEW

**Comment by timabell-gnf1** [comment]
Thanks for this! I totally don't keep on top of my github notifications. I just got a quick hack of this working before I noticed your pr, currently just built and uploaded locally.

I'll have a look at the pipeline stuff you've suggested, much appreciated. Learning lots here

**Comment by wgnf** [comment]
Always happy to help. Just hit me up if you need more information or anything else

**Comment by timabell** [comment]
Thanks again, I cherry-picked your commits into `main` and it's working great.

I added the GPL to the repo, could you confirm if you're happy for your contribution to this repo to be under that? It's only ci stuff, but best make sure we're on the same page.

**Comment by wgnf** [comment]
I'm fine with that yeah 👍
Happy to help

**Comment by timabell** [comment]
Fab, thanks!
I've added the same pipeline to SlnEditor, that's so cool.

**Pull request closed without merging**
